package com.am.reachwell.Assets.Constant;

public interface AssetConstant {
    int REQUEST_GET_ASSET_CLASS = 100;
    int REQUEST_GET_ASSET_STATUS = 101;
    int REQUEST_GET_ASSET_DETAILS_LIST = 102;
    int REQUEST_GET_AQUISITION_METHOD = 103;
    int REQUEST_GET_CONTRACT_TYPE = 104;
    int REQUEST_GET_ACCOUNT_HEAD = 105;
    int REQUEST_GET_LOCATION_TYPE = 106;
    int REQUEST_GET_LOCATION = 107;
    int REQUEST_CREATE_ASSET = 108;
    int REQUEST_GET_EMPLOYYES = 109;
    int REQUEST_GET_SUPPLIER = 110;
    int REQUEST_GET_ASSET_DETAIL = 111;
}
